# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-11 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttitle',
            name='at_type',
            field=models.CharField(choices=[(b'0', '\u5165\u91d1'), (b'1', '\u51fa\u91d1')], default=0, max_length=1, verbose_name='\u52d8\u5b9a\u79d1\u76ee\u7a2e\u985e'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_status',
            field=models.CharField(choices=[(b'0', '\u8a08\u753b\u4e2d'), (b'1', '\u5229\u7528\u4e2d'), (b'2', '\u5b8c\u4e86\u6e08'), (b'9', '\u524a\u9664\u6e08')], default=0, max_length=1, verbose_name='Project\u72b6\u614b'),
            preserve_default=False,
        ),
    ]
