# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-12 20:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountbook',
            name='trade_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 3, 12, 20, 2, 23, 824267, tzinfo=utc), null=True, verbose_name='\u53d6\u5f15\u65e5'),
        ),
        migrations.AlterField(
            model_name='accountbook',
            name='ab_desc',
            field=models.CharField(max_length=100, verbose_name='\u5e33\u7c3f\u6458\u8981'),
        ),
    ]
