# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-12 20:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170313_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbook',
            name='dw_type',
            field=models.CharField(choices=[(b'0', '\u5165\u91d1'), (b'1', '\u51fa\u91d1')], default=1, max_length=1, verbose_name='\u5165\u51fa\u91d1\u7a2e\u985e'),
        ),
        migrations.AlterField(
            model_name='accountbook',
            name='trade_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 3, 12, 20, 16, 53, 73003, tzinfo=utc), null=True, verbose_name='\u53d6\u5f15\u65e5'),
        ),
    ]
