# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-13 15:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170313_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbook',
            name='trade_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 3, 13, 15, 12, 15, 284884, tzinfo=utc), null=True, verbose_name='\u53d6\u5f15\u65e5'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(choices=[(b'0', '\u5229\u7528\u4e2d'), (b'1', '\u5b8c\u4e86\u6e08')], max_length=1, verbose_name='Project\u72b6\u614b'),
        ),
    ]
