# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-22 15:08
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_auto_20170318_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBookPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_month', models.DateField(blank=True, default='2017-03-01', null=True, verbose_name='\u53d6\u5f15\u65e5')),
                ('dw_type', models.CharField(choices=[(b'0', '\u5165\u91d1'), (b'1', '\u51fa\u91d1')], default=1, max_length=1, verbose_name='\u5165\u51fa\u91d1\u7a2e\u985e')),
                ('ab_desc', models.CharField(max_length=100, verbose_name='\u5e33\u7c3f\u6458\u8981')),
                ('ab_money', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999999)], verbose_name='\u5e33\u7c3f\u91d1\u984d')),
                ('at', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.AccountTitle', verbose_name='\u52d8\u5b9a\u79d1\u76ee')),
            ],
        ),
        migrations.AlterField(
            model_name='accountbook',
            name='trade_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 3, 22, 15, 8, 31, 992557, tzinfo=utc), null=True, verbose_name='\u53d6\u5f15\u65e5'),
        ),
        migrations.AlterField(
            model_name='depositwithdrawalmethod',
            name='dwm_type',
            field=models.CharField(blank=True, choices=[(b'0', '\u73fe\u91d1'), (b'1', '\u30af\u30ec\u30b8\u30c3\u30c8'), (b'2', '\u632f\u8fbc'), (b'3', '\u53e3\u5ea7\u632f\u66ff'), (b'4', '\u30dd\u30a4\u30f3\u30c8')], default=0, max_length=1, null=True, verbose_name='\u5165\u51fa\u91d1\u65b9\u6cd5\u7a2e\u985e'),
        ),
        migrations.AddField(
            model_name='accountbookplan',
            name='dwm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.DepositWithdrawalMethod', verbose_name='\u5165\u51fa\u91d1\u65b9\u6cd5'),
        ),
        migrations.AddField(
            model_name='accountbookplan',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Project', verbose_name='Project\u60c5\u5831'),
        ),
        migrations.AddField(
            model_name='accountbookplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
