# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-22 16:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20170323_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbook',
            name='trade_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 3, 22, 16, 9, 0, 890403, tzinfo=utc), null=True, verbose_name='\u53d6\u5f15\u65e5'),
        ),
        migrations.AlterField(
            model_name='accountbookplan',
            name='trade_date',
            field=models.CharField(default=b'2017-03', max_length=7, verbose_name='\u4e88\u5b9a\u5e74\u6708'),
        ),
    ]
