# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-22 16:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20170323_0113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountbookplan',
            old_name='trade_year_month',
            new_name='plan_year_month',
        ),
        migrations.AlterField(
            model_name='accountbook',
            name='trade_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 3, 22, 16, 29, 17, 174828, tzinfo=utc), null=True, verbose_name='\u53d6\u5f15\u65e5'),
        ),
    ]
