# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-24 14:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20170323_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbook',
            name='dwm',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.DepositWithdrawalMethod', verbose_name='\u5165\u51fa\u91d1\u65b9\u6cd5'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accountbook',
            name='trade_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 3, 24, 14, 30, 51, 209879, tzinfo=utc), null=True, verbose_name='\u53d6\u5f15\u65e5'),
        ),
    ]
