# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-24 15:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20170324_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountbookplan',
            name='ab_create_flag',
            field=models.CharField(choices=[(b'0', '\u672a\u4f5c\u6210'), (b'1', '\u4f5c\u6210\u6e08')], default=0, max_length=1, verbose_name='\u5e33\u7c3f\u4f5c\u6210\u30d5\u30e9\u30b0'),
        ),
        migrations.AlterField(
            model_name='accountbook',
            name='trade_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 3, 24, 15, 12, 20, 735674, tzinfo=utc), null=True, verbose_name='\u53d6\u5f15\u65e5'),
        ),
        migrations.AlterField(
            model_name='accountbookplan',
            name='dwm',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.DepositWithdrawalMethod', verbose_name='\u5165\u51fa\u91d1\u65b9\u6cd5'),
            preserve_default=False,
        ),
    ]
