# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-03 17:39
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20170404_0220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depositwithdrawalmethod',
            name='pay_deadline',
        ),
        migrations.AddField(
            model_name='depositwithdrawalmethod',
            name='pay_deadline_day',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='\u652f\u6255\u671f\u65e5(\u7de0\u3081\u5f8c\u65e5\u6570)'),
        ),
        migrations.AddField(
            model_name='depositwithdrawalmethod',
            name='pay_deadline_month',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='\u652f\u6255\u671f\u65e5(\u7de0\u3081\u5f8c\u6708\u6570)'),
        ),
        migrations.AlterField(
            model_name='accountbook',
            name='trade_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 4, 3, 17, 39, 25, 868940, tzinfo=utc), null=True, verbose_name='\u53d6\u5f15\u65e5'),
        ),
    ]
