# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-05 10:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20170405_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountbook',
            name='bab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.BankAccountBalance', verbose_name='\u9280\u884c\u53e3\u5ea7\u6b8b\u9ad8'),
        ),
        migrations.AlterField(
            model_name='accountbook',
            name='trade_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 4, 5, 10, 28, 43, 762959, tzinfo=utc), null=True, verbose_name='\u53d6\u5f15\u65e5'),
        ),
        migrations.AlterField(
            model_name='bankaccountbalance',
            name='trade_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 4, 5, 10, 28, 43, 761503, tzinfo=utc), null=True, verbose_name='\u53d6\u5f15\u65e5'),
        ),
    ]
