# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-05 17:23
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20170405_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbook',
            name='trade_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 4, 5, 17, 23, 40, 256710, tzinfo=utc), null=True, verbose_name='\u53d6\u5f15\u65e5'),
        ),
        migrations.AlterField(
            model_name='bankaccountbalance',
            name='money',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(-99999999), django.core.validators.MaxValueValidator(99999999)], verbose_name='\u91d1\u984d'),
        ),
        migrations.AlterField(
            model_name='bankaccountbalance',
            name='trade_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 4, 5, 17, 23, 40, 255130, tzinfo=utc), null=True, verbose_name='\u53d6\u5f15\u65e5'),
        ),
    ]
