# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-07 10:21
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0036_auto_20170406_0223'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dp_name', models.CharField(default=None, max_length=100, verbose_name='\u30c7\u30fc\u30bf\u30d1\u30bf\u30fc\u30f3\u540d')),
                ('sort_no', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)], verbose_name='\u8868\u793a\u9806')),
                ('at', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.AccountTitle', verbose_name='\u52d8\u5b9a\u79d1\u76ee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='accountbook',
            name='trade_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 5, 7, 10, 21, 45, 776561, tzinfo=utc), null=True, verbose_name='\u53d6\u5f15\u65e5'),
        ),
        migrations.AlterField(
            model_name='accountbookplan',
            name='plan_year_month',
            field=models.CharField(default=b'2017-05', max_length=7, verbose_name='\u4e88\u5b9a\u5e74\u6708'),
        ),
        migrations.AlterField(
            model_name='bankaccountbalance',
            name='trade_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 5, 7, 10, 21, 45, 775141, tzinfo=utc), null=True, verbose_name='\u53d6\u5f15\u65e5'),
        ),
    ]
