# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-07 14:21
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0039_auto_20170507_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPatternUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField(blank=True, default=datetime.datetime(2017, 5, 7, 14, 21, 8, 782333, tzinfo=utc), null=True, verbose_name='\u53d6\u5f15\u65e5')),
                ('at', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.AccountTitle', verbose_name='\u52d8\u5b9a\u79d1\u76ee')),
                ('dp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.DataPattern', verbose_name='DP')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='accountbook',
            name='trade_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 5, 7, 14, 21, 8, 774012, tzinfo=utc), null=True, verbose_name='\u53d6\u5f15\u65e5'),
        ),
        migrations.AlterField(
            model_name='bankaccountbalance',
            name='trade_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 5, 7, 14, 21, 8, 772617, tzinfo=utc), null=True, verbose_name='\u53d6\u5f15\u65e5'),
        ),
    ]
