# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-14 16:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_auto_20170507_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datapatternuse',
            name='dp',
        ),
        migrations.AddField(
            model_name='datapatternuse',
            name='desc',
            field=models.CharField(default=None, max_length=100, verbose_name='\u5e33\u7c3f\u6458\u8981'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accountbook',
            name='trade_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 5, 14, 16, 9, 28, 94940, tzinfo=utc), null=True, verbose_name='\u53d6\u5f15\u65e5'),
        ),
        migrations.AlterField(
            model_name='bankaccountbalance',
            name='trade_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 5, 14, 16, 9, 28, 93574, tzinfo=utc), null=True, verbose_name='\u53d6\u5f15\u65e5'),
        ),
        migrations.AlterField(
            model_name='datapatternuse',
            name='trade_date',
            field=models.DateField(default=datetime.datetime(2017, 5, 14, 16, 9, 28, 103238, tzinfo=utc), verbose_name='\u53d6\u5f15\u65e5'),
        ),
    ]
