# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-14 16:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_auto_20170515_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbook',
            name='trade_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 5, 14, 16, 10, 3, 294690, tzinfo=utc), null=True, verbose_name='\u53d6\u5f15\u65e5'),
        ),
        migrations.AlterField(
            model_name='bankaccountbalance',
            name='trade_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 5, 14, 16, 10, 3, 293316, tzinfo=utc), null=True, verbose_name='\u53d6\u5f15\u65e5'),
        ),
        migrations.AlterField(
            model_name='datapatternuse',
            name='desc',
            field=models.CharField(default=None, max_length=100, verbose_name='\u5e33\u7c3f\u6458\u8981'),
        ),
        migrations.AlterField(
            model_name='datapatternuse',
            name='trade_date',
            field=models.DateField(default=datetime.datetime(2017, 5, 14, 16, 10, 3, 302943, tzinfo=utc), verbose_name='\u53d6\u5f15\u65e5'),
        ),
    ]
