# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-15 15:45
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_auto_20170515_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapatternuse',
            name='money',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-99999999), django.core.validators.MaxValueValidator(99999999)], verbose_name='\u91d1\u984d'),
        ),
        migrations.AlterField(
            model_name='accountbook',
            name='trade_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 5, 15, 15, 45, 52, 454612, tzinfo=utc), null=True, verbose_name='\u53d6\u5f15\u65e5'),
        ),
        migrations.AlterField(
            model_name='bankaccountbalance',
            name='trade_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 5, 15, 15, 45, 52, 453226, tzinfo=utc), null=True, verbose_name='\u53d6\u5f15\u65e5'),
        ),
        migrations.AlterField(
            model_name='datapatternuse',
            name='trade_date',
            field=models.DateField(default=datetime.datetime(2017, 5, 15, 15, 45, 52, 462788, tzinfo=utc), verbose_name='\u53d6\u5f15\u65e5'),
        ),
    ]
