# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-22 15:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_auto_20170516_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapatternuse',
            name='ab',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.AccountBook', verbose_name='\u5e33\u7c3f\u60c5\u5831'),
        ),
        migrations.AlterField(
            model_name='accountbook',
            name='trade_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 5, 22, 15, 5, 33, 31615, tzinfo=utc), null=True, verbose_name='\u53d6\u5f15\u65e5'),
        ),
        migrations.AlterField(
            model_name='bankaccountbalance',
            name='trade_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 5, 22, 15, 5, 33, 30237, tzinfo=utc), null=True, verbose_name='\u53d6\u5f15\u65e5'),
        ),
        migrations.AlterField(
            model_name='datapatternuse',
            name='trade_date',
            field=models.DateField(default=datetime.datetime(2017, 5, 22, 15, 5, 33, 40075, tzinfo=utc), verbose_name='\u53d6\u5f15\u65e5'),
        ),
    ]
