# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-23 13:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_auto_20170523_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapatternuse',
            name='dwm',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.DepositWithdrawalMethod', verbose_name='\u5165\u51fa\u91d1\u65b9\u6cd5'),
        ),
        migrations.AlterField(
            model_name='accountbook',
            name='trade_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 5, 23, 13, 52, 3, 307025, tzinfo=utc), null=True, verbose_name='\u53d6\u5f15\u65e5'),
        ),
        migrations.AlterField(
            model_name='bankaccountbalance',
            name='trade_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 5, 23, 13, 52, 3, 305640, tzinfo=utc), null=True, verbose_name='\u53d6\u5f15\u65e5'),
        ),
        migrations.AlterField(
            model_name='datapatternuse',
            name='trade_date',
            field=models.DateField(default=datetime.datetime(2017, 5, 23, 13, 52, 3, 315378, tzinfo=utc), verbose_name='\u53d6\u5f15\u65e5'),
        ),
    ]
