# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-23 14:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_auto_20170523_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbook',
            name='trade_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 5, 23, 14, 2, 13, 169789, tzinfo=utc), null=True, verbose_name='\u53d6\u5f15\u65e5'),
        ),
        migrations.AlterField(
            model_name='bankaccountbalance',
            name='trade_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 5, 23, 14, 2, 13, 168414, tzinfo=utc), null=True, verbose_name='\u53d6\u5f15\u65e5'),
        ),
        migrations.AlterField(
            model_name='datapatternuse',
            name='desc',
            field=models.CharField(default=None, max_length=100, verbose_name='\u5e33\u7c3f\u6458\u8981'),
        ),
        migrations.AlterField(
            model_name='datapatternuse',
            name='dwm',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.DepositWithdrawalMethod', verbose_name='\u5165\u51fa\u91d1\u65b9\u6cd5'),
        ),
        migrations.AlterField(
            model_name='datapatternuse',
            name='trade_date',
            field=models.DateField(default=datetime.datetime(2017, 5, 23, 14, 2, 13, 178163, tzinfo=utc), verbose_name='\u53d6\u5f15\u65e5'),
        ),
    ]
