"""
Django settings for kakebo project.

Generated by 'django-admin startproject' using Django 1.9.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os
#add-start yama
import dj_database_url
#add-end yama

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
#add-start yama
PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))
#add-end yama

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '*v31%+49r_(arx))p+*ovvebe@yil&56-m)2794v6e8l$-7*f3'

# SECURITY WARNING: don't run with debug turned on in production!
#del-start yama
#DEBUG = True
#del-end yama
#add-start yama
DEBUG = (os.environ.get('PRODCUTION') != 'True')
TEMPLATE_DEBUG = (os.environ.get('PRODUCTION') != 'True')
#add-end yama

#del-start yama
#ALLOWED_HOSTS = []
#del-end yama
#add-start yama
ALLOWED_HOSTS = ['*']
#add-end yama

# Application definition

INSTALLED_APPS = [
    'common.apps.CommonConfig',
    'app.apps.AppConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bootstrapform',
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'kakebo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        #del-start yama
        #'DIRS': [],
        #del-end yama
        #add-start yama
        'DIRS': ['kakebo/templates'],
        #add-end yama
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'kakebo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

#add-start yama
db_from_env = dj_database_url.config(conn_max_age=400)
DATABASES['default'].update(db_from_env)
#add-end yama


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

#del-start yama
#LANGUAGE_CODE = 'en-us'
#
#TIME_ZONE = 'UTC'
#del-end yama
#add-start yama
LANGUAGE_CODE = 'ja-JP'
TIME_ZONE = 'Asia/Tokyo'
#add-end yama

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

#add-start yama
STATIC_ROOT = os.path.join(PROJECT_ROOT,'staticfiles')
STATICFILES_STORAGE = 'whitenoise.django.GzipManifestStaticFilesStorage'
#add-end yama


STATIC_URL = '/static/'

#add-start yama
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
)
#add-end yama

#add-start yama
LOGIN_REDIRECT_URL = '/common/mypage'
LOGIN_URL = '/common/login'
#add-end yama
